server:
  port: 8080

spring:
  main:
    headless: true
  profiles:
    active: ${ENVIRONMENT:local}
  data:
    mongodb:
      username: ${MONGO_USER:}
      password: ${MONGO_PASSWORD:}
      database: ${MONGO_ENV:}
      host: ${MONGO_ADDRESS:}

api:
  url: ${TARIFF_MANAGER_URL:}
  role: OTHER
  log-payload: ${TARIFF_MANAGER_LOG_PAYLOAD:false}
  collection-prefix: "TariffManager_"

platform:
  url: ${PLATFORM_URL:}
  party-id: ${PLATFORM_PARTY_ID:}
  country-code: ${PLATFORM_COUNTRY_CODE:}

hashing-service:
  url: ${HASHING_SERVICE_URL:}

springdoc:
  swagger-ui:
    path: /swagger-ui
    enabled: ${SWAGGER_ENABLED:true}
  api-docs:
    path: /api-docs
    enabled: ${SWAGGER_ENABLED:true}
