oli-app:
  fullnameOverride: "tariff-manager-int"
  image:
    tag: "main-5ee1365"
  ingress:
    hosts:
      - host: banula-int.oli-system.com
    tls:
      - secretName: banula-int-tls
        hosts:
          - banula-int.oli-system.com
    features:
      router:
        routes:
          exposeCommon: false
          exposeAll: true
