apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tariff-manager-int
  namespace: argocd
  labels:
    repo: banula-tariff-manager
spec:
  project: banula
  source:
    repoURL: https://github.com/olisystems/banula-tariff-manager.git
    targetRevision: main
    path: infra/helm
    helm:
      valueFiles:
        - values.yaml
        - values.int.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: banula-int
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
